name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on:
      ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          check-latest: true
      - name: Cache Gradle configuration
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            .gradle
            build
            fabric/.gradle
            fabric/build
            neoforge/.gradle
            neoforge/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/LICENSE') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Delete old files
        run: rm -rf build/libs fabric/build/libs neoforge/build/libs
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "fabric/build/libs/*.jar;neoforge/build/libs/*-all.jar"
          repo-token: ${{ secrets.GITHUB_TOKEN }}