name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "fabric/build/libs/*.jar;neoforge/build/libs/*-all.jar"
          repo-token: ${{ secrets.GITHUB_TOKEN }}